#!/bin/bash

ScriptDir=$(readlink -f $(dirname $0))
ScriptName=$(basename "$0")

# set up the path, "borrowed" from module
CmSlurmRoot=/cm/shared/apps/slurm/current
export PATH=${CmSlurmRoot}/bin:$PATH
export PATH=${CmSlurmRoot}/sbin:$PATH
export LD_LIBRARY_PATH=${CmSlurmRoot}/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${CmSlurmRoot}/lib64/slurm:$LD_LIBRARY_PATH
PLHACK="LD_PRELOAD=${CmSlurmRoot}/lib64/slurm/libslurmfull.so"

# activate python virutal environment
# popeye modified
. /mnt/home/yliu/projects/slurm/utils/env_popeye_python39/bin/activate
echo "Using: $(which python)"

# set up the log directory
logDir="./log"
mkdir -p ${logDir}  || { echo "Failed to create support directory." ; exit 1 ; }

# popeye modified
declare -a cmds=("python ${ScriptDir}/mqttMonStream.py -c config/config_popeye.json" "python ${ScriptDir}/mqttMon2Influx.py -c config/config_popeye.json")

echo "Start programs ..."
for program in "${cmds[@]}"
do
    echo -e "\t $program &"
    $program &
done

sleep 10
#loop to check if each program is running
while true
do
   #check the status of each program
   for program in "${cmds[@]}"
   do
      # Get the porcess ID of the program
      pid=$(pgrep -f "$program")
      
      # If the process ID is not found, restart the program
      if [ -z "$pid" ]
      then
	 echo "$(date '+%D %H:%M:%S') $program has died. Restarting ..."
	 $program &
      fi
   done

   #Wait for a minute before checking again
   sleep 60
done > "${logDir}/${ScriptName}_$(date +%Y%m%d).log" 2>&1 &


